### ISSUE TITLE
Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by zenandreas** [BentoBoxWorld/addon-bskyblock#20]
[20:05:11] [Server thread/ERROR]: Could not load 'plugins/BSkyBlock-0.3.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:320) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by tastybento** [comment]
@bertek41 is correct.
